I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script call
    call cardgame1 from _call_cardgame1
  File "game/cardgame.rpy", line 730, in script
    python:
  File "game/cardgame.rpy", line 738, in <module>
    b1[0].battlecard_bottom_to_top()
AttributeError: 'card' object has no attribute 'battlecard_bottom_to_top'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script call
    call cardgame1 from _call_cardgame1
  File "game/cardgame.rpy", line 730, in script
    python:
  File "E:\Downloads 2\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\Downloads 2\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/cardgame.rpy", line 738, in <module>
    b1[0].battlecard_bottom_to_top()
AttributeError: 'card' object has no attribute 'battlecard_bottom_to_top'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Triple Triad 1.0
Sun Nov 01 02:01:04 2020
